[workspace]
members = [
    "crates/*",
    "examples/hello_world",
    "examples/real_project_layout/*",
    "tests"
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.95"
darling = "0.20.10"
derive_builder = "0.20.2"
heck = "0.5.0"
log = "0.4.14"
proc-macro2 = "1.0.36"
quote = "1.0.15"
serde = "1.0.203"
syn = "2.0.79"

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 } # We might want to disable this if it causes issues.

option_if_let_else = "allow" # trips up on `darling`
match_same_arms = "allow" # too many
missing_const_for_fn = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
default_constructed_unit_structs = "allow"
