[package]
name = "interoptopus_backend_cpython"
description = "Generates CPython bindings."
version = "0.15.0-alpha.4"
edition = "2024"
license = "MIT"
keywords = ["ffi", "code-generation", "bindings", "python"]
categories = ["api-bindings", "development-tools::ffi"]
documentation = "https://docs.rs/interoptopus_backend_cpython/"
repository = "https://github.com/ralfbiedert/interoptopus"

[lints]
workspace = true

[dependencies]
interoptopus.workspace = true
derive_builder.workspace = true
