[package]
name = "interoptopus_backend_csharp"
description = "Generates C# bindings."
version = "0.1.5"
edition = "2018"
license = "MIT"
documentation = "https://docs.rs/interoptopus_backend_csharp/"
repository = "https://github.com/ralfbiedert/interoptopus"


[dependencies]
interoptopus = { path = "../interoptopus", version = "0.1" }

[dev-dependencies]
interoptopus_reference_project = { path = "../interoptopus_reference_project", version = "0.1" }
