[package]
name = "core_library_ffi"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
core_library = { path = "../core_library" }
interoptopus = { path = "../../../crates/core" }
