[package]
name = "interoptopus"
description = "ğŸ¦€ â†’ ğŸ™ â†’ Python, C#, C, â€¦ FFI bindings to your favorite language. Composable. Escape hatches included."
authors = ["Ralf Biedert <rb@xr.io>"]
version = "0.1.5"
edition = "2018"
license = "MIT"
documentation = "https://docs.rs/interoptopus/"
repository = "https://github.com/ralfbiedert/interoptopus"

[features]
derive = ["interoptopus_proc"]
testing = ["cc"]

[dependencies]
interoptopus_proc = { path = "../interoptopus_proc", version = "0.1", optional = true }
cc = { version = "1.0.68", optional = true }

[dev-dependencies]
interoptopus_backend_csharp = { path = "../interoptopus_backend_csharp", version = "0.1" }
