[package]
name = "interoptopus"
description = "The polyglot bindings generator for your library (C#, C, Python, ...). üêô"
authors = ["Ralf Biedert <rb@xr.io>"]
keywords = ["ffi", "code-generation", "bindings"]
categories = ["api-bindings", "development-tools::ffi"]
version = "0.14.27"
edition = "2021"
rust-version = "1.83"
license = "MIT"
documentation = "https://docs.rs/interoptopus/"
repository = "https://github.com/ralfbiedert/interoptopus"

[lints]
workspace = true


[features]
default = ["derive"]
derive = ["interoptopus_proc"]

[dependencies]
interoptopus_proc = { path = "../proc_macros", version = "0.14.0", optional = true }
log = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

