[package]
name = "interoptopus"
description = "The polyglot bindings generator for your library (C#, C, Python, ...). üêô"
authors.workspace = true
keywords = ["ffi", "code-generation", "bindings"]
categories = ["api-bindings", "development-tools::ffi"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
documentation = "https://docs.rs/interoptopus/"
repository.workspace = true

[lints]
workspace = true

[features]
default = ["derive"]
derive = ["interoptopus_proc"]

[dependencies]
interoptopus_proc = { path = "../proc_macros", version = "0.15.0-alpha.12", optional = true }
log = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
tera = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rustc-hash = { version = "2.1", default-features = false }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
