[package]
name = "interoptopus_backend_csharp"
description = "Generates C# bindings."
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords = ["ffi", "code-generation", "bindings", "csharp", "dotnet"]
categories = ["api-bindings", "development-tools::ffi"]
documentation = "https://docs.rs/interoptopus_backend_csharp/"
repository.workspace = true

[lints]
workspace = true

[features]
serde = []

[dependencies]
interoptopus = { path = "../core", version = "0.15.0-alpha.12" }
heck = { workspace = true }
derive_builder = { workspace = true }
tera.workspace = true
include_dir.workspace = true
indent.workspace = true
