[package]
name = "interoptopus_backend_csharp"
description = "Generates C# bindings."
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords = ["ffi", "code-generation", "bindings", "csharp", "dotnet"]
categories = ["api-bindings", "development-tools::ffi"]
documentation = "https://docs.rs/interoptopus_backend_csharp/"
repository.workspace = true

[lints]
workspace = true

[dependencies]
derive_builder = { workspace = true }
heck = { workspace = true }
include_dir = { workspace = true }
interoptopus = { workspace = true }
interoptopus_backend_utils = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tera = { workspace = true }
